cache Failed: string(38) "get failed with result mc_res_notfound"
one Success: int(1)
